version: '2'

services:
    fastapi:
        build:
            context: .
            dockerfile: docker/Dockerfile-fastapi
        volumes:
            - "."
        environment:
            - PYTHONUNBUFFERED=0
            - PYTHONPYCACHEPREFIX=../__pycache__
        ports:
            - "8000:8000"
        command: uvicorn main:app --reload
