# Development Dockerfile for FastAPI app

FROM python:3.9-slim

# Set the default directory where CMD will execute
WORKDIR /app

# Run FastAPI's runserver by default
CMD ["uvicorn", "main:app", "--reload"]

# Install dependencies from requirements file
COPY requirements.txt .
RUN pip install -r requirements.txt
